name: Build & Deploy
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Set environment variables
        run: |
          if [[ ${GITHUB_REF##*/} == 'master' ]]; then
            echo "S3BUCKET=dobbyprod" >> "$GITHUB_ENV"
          else
            echo "S3BUCKET=dobbystage" >> "$GITHUB_ENV"
          fi

          echo $S3BUCKET

      - name: Setup dependencies
        run: npm install -g yarn @quasar/cli

      - name: Install
        run: yarn install
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Build project
        run: quasar build
      
      - name: Copy .env file
        run: (test -f env.${GITHUB_REF##*/} && cp -v env.${GITHUB_REF##*/} dist/spa/.env) || echo "File env.${GITHUB_REF##*/} does not exist"
      
      - name: Generate release variables
        run: |
          echo "CURRENT_RELEASE=$(git rev-parse --short $GITHUB_SHA)" >> dist/spa/.env

      - name: Sync files to s3
        run: aws s3 sync --delete dist/spa/ s3://${S3BUCKET} && aws cloudfront create-invalidation --distribution-id=${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths='/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
