name: Build & Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: https://npm.fontawesome.com/
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup dependencies
        run: npm install -g yarn quasar
      - name: Install
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_FA_TOKEN}}
      - name: Build project
        run: quasar build
